import React from 'react';

export default function SwimmingPaceCalculatorContent() {
  return (
    <article className="space-y-6 text-gray-700 leading-relaxed">
      <section>
        <h2 className="text-3xl font-bold text-gray-900 mb-4 mt-8 first:mt-0">Swimming Pace Calculator</h2>
        <p className="mb-4 text-lg leading-7">
          The Swimming Pace Calculator helps swimmers and coaches determine pace per 100 meters and generate split times for standard segments (50m). Enter the total distance swum and the total time to automatically compute your pace and splits. This tool is useful for pacing strategy, interval sets, and progress tracking, making it an essential resource for any swimmer or coach.
        </p>
      </section>

      <section>
        <h2 className="text-3xl font-bold text-gray-900 mb-4">Understanding Swimming Pace</h2>
        <p className="mb-4 text-lg leading-7">
          In swimming, pace is a crucial factor that can influence performance and training effectiveness. By understanding how to calculate your swimming pace, you can manage your energy better during workouts and competitions. This calculator not only provides immediate feedback but also encourages swimmers to reflect on their efforts, which ultimately leads to improvement and faster race times.
        </p>
      </section>

      <section>
        <h3 className="text-2xl font-semibold text-gray-900 mb-3">How it works</h3>
        <p className="mb-4 text-lg leading-7">
          Internally, the calculator computes a base pace in seconds per meter (total time ÷ distance), then converts that to seconds per 100 meters. Splits are generated by multiplying the base seconds-per-meter by the segment distance (50m by default). This ensures accuracy and consistent unit handling.
        </p>

        <div className="bg-gray-50 border-l-4 border-blue-500 p-4 my-4 rounded-r">
          <code className="text-base font-mono text-gray-900">pacePer100m = (totalTime / distance) × 100</code>
        </div>

        <p className="mb-4 text-lg leading-7">
          The calculator updates automatically as you change the inputs — no manual "calculate" button required. Use the chart toggle to visualize split times across the swim distance effectively. This feature can prove invaluable during training sessions and provides clear insights into performance.
        </p>
      </section>

      <section>
        <h3 className="text-2xl font-semibold text-gray-900 mb-3">Example</h3>
        <p className="mb-4 text-lg leading-7">
          If you swim 100 meters in 60 seconds, the calculator computes your pace as 60 seconds per 100m (1:00). For a 200m swim in 150 seconds, pace per 100m would be 75 seconds (1:15). The splits section breaks the total distance down into 50m segments and shows expected times for each. 
        </p>

        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mt-4">
          <p className="text-base text-gray-700">
            Example: 100m in 60s → pace = (60 / 100) × 100 = 60s per 100m → displayed as 1:00 per 100m.
          </p>
        </div>
      </section>

      <section>
        <h3 className="text-2xl font-semibold text-gray-900 mb-3">Use Cases</h3>
        <p className="mb-4 text-lg leading-7">
          The Swimming Pace Calculator is versatile for various scenarios. Coaches can use it to develop tailored training sessions that fit the needs of their swimmers. Likewise, swimmers can apply the tool to set personal goals, track their progress over time, and understand their pacing better to improve performance in competitions.
        </p>
      </section>

      <section>
        <h3 className="text-2xl font-semibold text-gray-900 mb-3">Frequently Asked Questions</h3>

        <div className="mt-4">
          <h4 className="text-lg font-medium">What if I enter an invalid value?</h4>
          <p className="mb-4 text-lg leading-7">The calculator requires positive numeric values for distance and time. If inputs are invalid or zero, results and charts will not be shown, ensuring that users always receive meaningful feedback.</p>

          <h4 className="text-lg font-medium">Can I change split length?</h4>
          <p className="mb-4 text-lg leading-7">This tool uses 50m splits by default, which are common in pool training. For different split lengths, you can adapt the calculation logic or use the outputs to manually compute other split sizes. Customizing these settings can enhance training strategies.</p>

          <h4 className="text-lg font-medium">Why is pace shown per 100m?</h4>
          <p className="mb-4 text-lg leading-7">Swimming performance is commonly reported as time per 100 meters, which makes it easy to compare efforts across different distances and training sets. Understanding this standard helps in evaluating and identifying areas for improvement in swimming technique and speed.</p>
        </div>
      </section>

      <section>
        <h3 className="text-2xl font-semibold text-gray-900 mb-3">Tips for Coaches and Swimmers</h3>
        <ul className="list-disc pl-5 space-y-2">
          <li>Use the pace to set interval times for training sets (e.g., target 1:10 per 100m → set intervals accordingly).</li>
          <li>Compare split symmetry to assess consistency across a swim.</li>
          <li>Download the PDF summary to share with athletes or to log session data, ensuring comprehensive tracking of performance progress.</li>
          <li>Incorporate pace training in your drills to improve overall efficiency in the water.</li>
          <li>Encourage swimmers to familiarize themselves with their pace to develop a competitive edge during races.</li>
        </ul>
      </section>
    </article>
  );
}
